### ISSUE TITLE
Big Picture auto starts on every game launch

### ISSUE THREAD

**Issue by tscolin** [FrogTheFrog/moondeck#11]
Big Picture mode is always starting behind every game when i use the moondeck shortcut.  Also controls are non-functional when this happens as controls dont work in big picture mode.

Windows 11, latest sunshine and moondeck/moondeck-buddy.

**Comment by FrogTheFrog** [comment]
> Big Picture mode is always starting behind every game when i use the moondeck shortcut.

This is not a bug, it's a feature.

> Also controls are non-functional when this happens as controls dont work in big picture mode.

This is an issue between sunshine and moonlight. All MoonDeck does is start the Moonlight client and a game on a host. Checkithis thread, maybe you have the same problem https://github.com/FrogTheFrog/moondeck/issues/10

**Comment by FrogTheFrog** [comment]
Closing the issue due to inactivity.

**Comment by PlotTwisted** [comment]
anyway to disable this "feature"?

**Comment by FrogTheFrog** [comment]
> anyway to disable this "feature"?

Please download Buddy from this build, run it once and there will be a new config value in the `settings.json`. Set the obvious new value to `false` and start the Buddy again.

Let me know about the experience (I also did not have time to test this at all).

The reason BigPicture is used is that is skips the launchers and other stuff. You need to click trough them fast, otherwise MoonDeck will timeout while waiting for the game to launch.

**Comment by MyNameHand** [comment]
@FrogTheFrog Sorry for the rather late reply even though you were so quick to respond. Finally got around to testing it today, it's great. It's exactly what I needed/wanted, thank you.
