### ISSUE TITLE
[Feature Request] Automatically suspend host PC when gaming session ends

### ISSUE THREAD

**Issue by KingIzzymon** [FrogTheFrog/moondeck#18]
Could you add the following options to 'Host Settings'?
- "Automatically suspend host PC when gaming session ends" true/false
  - "Return host to previous power state (example: host remains awake if it was on before the game session started)" true/false

**Comment by FrogTheFrog** [comment]
I have already considered something similar, but there are hard questions that I don't want to think about, such as:
- The stream is terminated via Sunshine/Moonlight, but the game is still running - suspend or no?
- The game is no longer running, but the Sunshine/Moonlight session is still active for some reason (from Buddy's perspective) - suspend or no?
- What happens if the connection is lost for a long time, does it mean that the gaming session has ended?

There are also some other edge cases that make it hard to properly implement, therefore I will not implement this feature. However, you're free to try to get this working yourself and create a PR.

**Comment by KingIzzymon** [comment]
Makes sense. I was figuring just keeping it simple in that, "if stream started from SteamDeck, and if stream closed by steam deck, then handle options X, Y, Z".

If I have time, I'll work on this but going to prioritize simplifying setup. That way your plugin has more potential visibility/contributors.

**Comment by FrogTheFrog** [comment]
Just a tip if you're going to try to implement this is you need to implement it in Buddy first. PcControl is the class you would be looking for to edit somehow.
