### ISSUE TITLE
Feature Request - Force 60hz on host

### ISSUE THREAD

**Issue by Genadiii** [FrogTheFrog/moondeck#20]
Is it possible to force the host to 60hz during streaming? 240hz is pointless when streaming to deck.

**Comment by FrogTheFrog** [comment]
I will not add this feature. Resolution changing is an exception since I wanted to do this dynamically, but my plan is to do as little as possible that involves reinventing the wheel (since I hope the Moonlight implements these features in the future).

However, you can do this and much more using Sunshine! Use the do/undo commands to change the refresh rate to whatever you want using `qres.exe`: https://winaero.com/change-display-refresh-rate-windows-10/

That aside, I would recommend keeping 240Hz refresh rate and using a global FPS limiter instead. It feels smoother for me this way.
