### ISSUE TITLE
FEATURE REQUEST: DUPLICATE SHORTCUT DETECTION

### ISSUE THREAD

**Issue by Rumik** [FrogTheFrog/moondeck#56]
Hi there,

I prefer to use Sunshine app shortcuts, rather than the MoonDeck button, but every time I Sync my Sunshine apps, duplicate shortcuts get created for the apps I already have shortcuts for. Would it be possible to detect existing shortcuts so duplicates don't get created?

Thanks.

**Comment by FrogTheFrog** [comment]
What exactly is the issue here? Can you give me an example?
Are you talking about `non-moondeck shortcuts vs moondeck shortcuts` or `moondeck shortcuts vs moondeck shortcuts`. The second case should not happens as the shortcuts should be cleaned up/replaced. If that is not the case, then it's a bug.

**Comment by Rumik** [comment]
Hi again!

Actually I think I was mistaken. I've used the feature several more times and I haven't had any more issues. So this can be closed.
