### ISSUE TITLE
Understanding closing games

### ISSUE THREAD

**Issue by justin-delano** [FrogTheFrog/moondeck#62]
Hi, I'm not sure the best way to end sessions. I maybe have some settings incorrectly configured as well. Things I've tried:

- Moonlight quit command: ends stream, but game remains on host PC
- Quit from steamdeck menu: ends stream, but game remains on host PC
- ALT-F4 from host PC: ends game, but not stream
- Quit from game menu (eg.  Elden Ring): works as expected, game ends, then stream ends

Closing steam when gaming session ends doesn't seem to work, since closing steam doesn't close all games necessarily. I've also disabled the sunshine settings (I think?) to not continue streaming when a connection is lost (image attached below from [Apollo](https://github.com/ClassicOldSong/Apollo))

Thanks in advance!

![image](https://github.com/user-attachments/assets/21f3528e-582b-44bd-be97-58950fbee40d)

**Comment by FrogTheFrog** [comment]
Does alt-f4 really not work? Even after you wait a little?

That aside everything is as expected. MoonDeck does not close games due to a simple reason - if the connection is lost, it would be stupid to forcefully close the game and also lose all the progress. It's also difficult to close apps properly 😔

**Comment by FrogTheFrog** [comment]
Just close the game on the host normally as intended when you're really done playing. Only SteamDeck has this magic where it can put the game into the memory and resume it on demand.

Killing the game via alt-f4 or otherwise is also not recommended. Windows does not give almost any time to react to this forced close. It could lead to a save corruption if you do this while game is doing auto-save or something.

**Comment by TeddOravec** [comment]
Just in case you are not aware, if you launch the game through PlayNite with the PlayState plugin installed you can “suspend” the game at will. This stops the PC from allowing CPU cycles to the game, so as far as it can tell time freezes, a la deck’s sleep mode. If you then disconnect the session and reconnect later, hit your controller hotkey and your game comes right back to life as if nothing happened

**Comment by FrogTheFrog** [comment]
> Just in case you are not aware, if you launch the game through PlayNite with the PlayState plugin installed you can “suspend” the game at will. This stops the PC from allowing CPU cycles to the game, so as far as it can tell time freezes, a la deck’s sleep mode. If you then disconnect the session and reconnect later, hit your controller hotkey and your game comes right back to life as if nothing happened

I was not aware that PlayNite was capable of doing this.

Suspending a process nothing new, however suspending + going to a sleep mode is where SteamDeck shines. It was always a lottery for me on Windows whether it will be properly restored or will just crash. Maybe it has changed since the last time I've tried.
